### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by mxa** [fundevogel/we-love-colors#14]
in the readme the command 
```
colors fetch --all && colors process
```
 is given as an example. However:

```
Usage: colors fetch [OPTIONS] [BRANDS]...
Try 'colors fetch -h' for help.

Error: no such option: --all
```
It seems that's not a correct syntax. Either a bug with the software or the documentation.

**Comment by S1SYPHOS** [comment]
I'll look into it, thanks @mxa!

**Comment by S1SYPHOS** [comment]
Well, just run `colors fetch`, which loads all sets by default 🦊 

Let me know if that helps @mxa

**Comment by S1SYPHOS** [comment]
@mxa I am closing this issue. If this problem persists, feel free to reopen / let me know!

Thanks for your initial report, I'm always glad to receive feedback.
