### ISSUE TITLE
Fetching & Processing will sometimes only produce .JSON

### ISSUE THREAD

**Issue by AaronMishaling** [fundevogel/we-love-colors#15]
Doing 'colors fetch --all && colours process' doesn't seem to work. 'colors fetch && colors process' seems to get .JSONS for all apart from copic and prismacolour which seems to not have an attribute called 'fetch_all'? Doing the colours individually does the same, except pantone and dulux now add all the other file formats; ral stays the same at just .JSON?

 - OS: Ubuntu 20.04 running KDE Plasma 5.18.5

Looks like an interesting project. I work as admin/marketing for a window/door company so RAL in GIMP is a timesaver, so I will be grateful to any help :)

Aaron

**Comment by S1SYPHOS** [comment]
As I recall correctly, just call `colors fetch`, without `--all` - let me know if that works, otherwise please provide your error log :fox_face:

**Comment by S1SYPHOS** [comment]
@AaronMishaling I saw that you've given this project a star, so I guess my suggestion worked for you?

Closing this issue, thanks again!
