### ISSUE TITLE
Colors references in Gimp

### ISSUE THREAD

**Issue by lalebarde** [fundevogel/we-love-colors#16]
I have imported the pantome colors in Gimp, but their references are missing. When I have chosed colors and designed with them, I need to provide their pantome references to printers.

Would it be possible to get the pantome references in Gimp?

**Comment by S1SYPHOS** [comment]
Could you please explain what exactly you need, maybe give an example?

Did you have a look at the generated files? And if so, which property is missing?

**Comment by S1SYPHOS** [comment]
@lalebarde Could you point me to the config property you are missing? Sorry for pinging you, it seemed my question from last week didn't quite make all the way 🦊
