### ISSUE TITLE
some minor problems

### ISSUE THREAD

**Issue by Il-Saggio** [fundevogel/we-love-colors#17]
Hello!

I have some minor problems with We love colors! :

in the file that generates the gpl files the xml rows should be modified to add one # after each \n ->  <'xml': '\n  #  PANTONE® and related trademarks are the property of\n  #  Pantone LLC (https://www.pantone.com), a division of X-Rite, a Danaher company\n  '>
Otherwise the file is not read by inkskape

fetching prismacolor causes an error in cli.py 

copic website has been moved and updated, so trying to extract data outputs an error

<colors fetch --all> outputs an error, claiming that the option does not exist. I think that once upon a time the option must have been eliminated for a simpler: no args=all, but in the readme.md it has not been updated.

For some mysterious causes: <colors fetch && colors process> does not work (on my linux Manjaro at least) It executes the first command and stops. Probably the first does not output anything and the && stops

By the way: thanks for the nice script, it does a very useful job!!!

**Desktop (please complete the following information):**
 - OS:  Manjaro Linux

PS
I just don't know how to send a suggestion, so I append here:
Any chance to get an update with NCS palette?
https://www.e-paint.co.uk/NCS-2050-index-colour-chart.asp
https://ncscolour.com/product-category/shop/colour-samples/
:) Thanks!

**Comment by S1SYPHOS** [comment]
Hey there!

First of all: Thank you very much! 🎉

It's been a while since we wrote this script, and haven't used or relied on it that much tbh. It was foreseeable that the scraped pages would change someday - BUT given your expressed interest, we'll consider fixing the issues you pointed out - big thanks!

Cheers
S1SYPHOS

**Comment by Il-Saggio** [comment]
That script should be more known, the basic palettes in inkskape are only directed to webdesigners, while the program could be really useful to many other illustrators. Having some standard colours "native" could get new quality users!

________________________________
Da: Martin Folkers ***@***.***>
Inviato: mercoledì 25 gennaio 2023 09:29
A: fundevogel/we-love-colors ***@***.***>
Cc: Il-Saggio ***@***.***>; Author ***@***.***>
Oggetto: Re: [fundevogel/we-love-colors] some minor problems (Issue #17)


Hey there!

First of all: Thank you very much! 🎉

It's been a while since we wrote this script, and haven't used or relied on it that much tbh. It was foreseeable that the scraped pages would change someday - BUT given your expressed interest, we'll consider fixing the issues you pointed out - big thanks!

Cheers
S1SYPHOS

**Comment by S1SYPHOS** [comment]
@Il-Saggio Hey there, I just want to let you know that I started working on it. This repository [is a mirror](https://codeberg.org/Fundevogel/we-love-colors), but you can totally check out any progress here. I will also look into NCS colors! :wink:

**Comment by S1SYPHOS** [comment]
@Il-Saggio I just released v2.0.0 to PyPI :partying_face: 

I changed the namespace to `farben` (german for 'colors') which makes it easy to remember and unifies package name and command. Have a look and feel free to give feedback at any time, it's much appreciated!

**Comment by S1SYPHOS** [comment]
FYI v2.1.0 brings support for 'HKS' colors as well

**Comment by Il-Saggio** [comment]
GREAT!! 
I'll upgrade as soon as I can! ;)

**Comment by S1SYPHOS** [comment]
I'd definitely love to get some feedback if that's alright! And if you encounter any kind of bug or odd behaviour, just let me know 😉
