### ISSUE TITLE
Add support for sK1 2.0 palettes (SKP)

### ISSUE THREAD

**Issue by ghost** [fundevogel/we-love-colors#6]
**Describe the solution you'd like**

Add support for SKP pallettes.

- *sK1 2.0* - https://github.com/sk1project/sk1-wx
- Nightly builds - http://downloads.sk1project.net/sk1/nightbuilds/

**Describe alternatives you've considered**

Add `we-love-colors` plugin for *sK1 2.0*; this is mostly task for @sk1project

**Additional context**

Here is free (Public Domain) palettes collection in SKP and other formats:

- Description - https://sk1project.net/palettes.php
- Downloads - http://downloads.sk1project.net/palettes/v1.0/

**Comment by S1SYPHOS** [comment]
I will look into it and let you know. Until then, pull requests are always appreciated :fox_face:

**Comment by S1SYPHOS** [comment]
Well, it seems that sk1 is already able to import color palettes being generated by this project, eg `gpl` (GIMP). I guess mentioning this would be enough?
