### ISSUE TITLE
Trouble Outputting a GPL file

### ISSUE THREAD

**Issue by themajestickoala** [fundevogel/we-love-colors#8]
**Describe the bug**
Processing the outputted JSON's does not work out and leaves user with unusable json files

**To Reproduce**
1. Fetch pantones or any other color
2. Submit process command

**Expected behavior**
Should output a .gpl

**Screenshots**
![image](https://user-images.githubusercontent.com/33986539/96037286-40e40500-0e2b-11eb-9282-0531c0876156.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

Might just be me, im just trying to get a gpl file and all i have is the json, Thank you!

**Comment by S1SYPHOS** [comment]
I'll have a look at this. Thanks for letting me know!

**Comment by toccata10** [comment]
python main.py process dulux pantone ral -f xml
allows to create the scribus file, otherwise, there's the "NoneType" error.

**Comment by S1SYPHOS** [comment]
Thanks for letting me know. Since I cannot test this on Windows (yet), I'll double-check the code again.

**Comment by toccata10** [comment]
I'm on Archlinux. 
I first tried `python main.py fetch --all && python main.py process` but there was a ssl certificate problem with copic and prismacolor.
So I tried to process manually the downloaded swatches by `python main.py process ral`
```
Traceback (most recent call last):
  File "/home/jo/tmp/welovecolor/we-love-colors-master/main.py", line 93, in <module>
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jo/tmp/welovecolor/we-love-colors-master/main.py", line 83, in process
    make_palette = getattr(object, 'make_' + format, None)
TypeError: can only concatenate str (not "NoneType") to str
```
I did not investigate further as giving the output format worked
`python main.py process ral -f xml`
Thanks for your nice project: it was very useful for me to get some xml swatches for Scribus.

**Comment by S1SYPHOS** [comment]
Glad it was useful to you 🦊 

I'll investigate nonetheless, I guess some source's markup changed or whatever ..

**Comment by S1SYPHOS** [comment]
@themajestickoala @toccata10
This issue is now fixed. I realise that it's been a while since you opened this issue, nonetheless I feel grateful for your effort and wanted to let you know of today's progress.

Thanks guys, stay healthy and spread the love!
